# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  command = "yarn build:testnet"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.5
    accessibility = 0.8
    best-practices = 0.8
    seo = 0.7
    pwa = 0

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
